config/routes.rb
ProjetoFinal::Application.routes.draw do
  resources :boletim_urnas
  resources :audits
  resources :district_audits do
    get 'show_in_table' => 'district_audits#show_in_table'
  end
  resources :cities, only: [:index]
  resources :bu, controller: :bulletin_urns_candidates_electoral_sections_political_parties

  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/bulletin_urns_candidates_electoral_sections_political_parties_controller.rb
class BulletinUrnsCandidatesElectoralSectionsPoliticalPartiesController < ApplicationController

  def index
    @bus = BulletinUrnsCandidatesElectoralSectionsPoliticalParties.all.order(:electoral_section_id,:candidate_id).limit(50)
  end

  def edit
    @bu = BulletinUrnsCandidatesElectoralSectionsPoliticalParties.find(params[:id])
  end

  def update
    @bu = BulletinUrnsCandidatesElectoralSectionsPoliticalParties.find(params[:id])
    if @bu.update_attributes(bu_params) then
      redirect_to action: :index
    else
      render :edit
    end
  end

  private
    def bu_params
      params.require(:bulletin_urns_candidates_electoral_sections_political_parties).permit(:vote_amount)
    end



end

app/views/bulletin_urns_candidates_electoral_sections_political_parties/edit.html.erb
<h1>Boletim de Urna</h1>

<%= form_for @bu, url: bu_path(@bu.id) do |f|%>
  <%= f.label 'Quantidade de Votos' %>
  <%= f.text_field :vote_amount %>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/bulletin_urns_candidates_electoral_sections_political_parties/index.html.erb
<h1>Boletim de Urna</h1>
<% old_electoral_section = 0 %>
<table class='table'>
  <tr>
    <th>Candidato </th>
    <th>Zona</th>
    <th>Sessão</th>
    <th>Quantidade de Votos</th>
    <th>Número de Votos</th>
    <th>Total de Votantes</th>
  <tr>
<% @bus.each do |bu| %>
  <% if old_electoral_section != bu.electoral_section_id %>
    <tr><td><br></td></tr>
  <% end %>
  <% old_electoral_section = bu.electoral_section_id %>
  <tr>
    <td><%= bu.candidate.name %></td>
    <td class='center'><%= bu.electoral_section.zone %></td>
    <td class='center'><%= bu.electoral_section.section %></td>
    <td class='center'><%= bu.vote_amount %></td>
    <td class='center'><%= bu.electoral_section.elections_electoral_section.number_of_voters_appeared %></td>
    <td class='center'><%= bu.electoral_section.elections_electoral_section.number_of_voters %></td>
    <td><%= link_to 'edit', edit_bu_path(bu.id) %></td>
  </tr>
<% end %>