config/routes.rb
ProjetoFinal::Application.routes.draw do
  resources :boletim_urnas
  resources :audits
  resources :district_audits do
    get 'show_in_table' => 'district_audits#show_in_table'
  end
  resources :cities, only: [:index]
  resources :bu, controller: :bulletin_urns_candidates_electoral_sections_political_parties

  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/district_audits_controller.rb
class DistrictAuditsController < ApplicationController
  before_action :load_resources, only: [:show, :show_in_table]
  # GET /district_audits
  # GET /district_audits.json
  def index
    @states = ElectoralSection.group(:state).order(:state).pluck(:state)
    @process = redis.keys("audit_*").collect{|k| JSON::parse(redis.get(k)).merge(id: k.split('_').last) }
  end

  def create
    @ubs = ElectoralSection.where({state: audit_params[:state], city: audit_params[:city]}).group("district").pluck(:district)
    redis_key = 'audit_'+ Digest::MD5.hexdigest(audit_params.to_json)
    if redis.get(redis_key).blank? && @ubs.any?
      redis.set(redis_key, { params: audit_params, total: @ubs.count}.to_json)
      @ubs.each{|ub|
         AuditWorker.perform_async({q: {electoral_section_state_eq: audit_params[:state], electoral_section_city_eq: audit_params[:city],
            electoral_section_district_eq: ub}}, redis_key: redis_key)
      }
    end

    redirect_to action: :index
  end

  def show

  end

  def show_in_table
    @candidates = @results.first["candidates"].sort{|a,b| a["candidate_name"]<=>b["candidate_name"] }
  end

  private
    def audit_params
      params.require(:audit).permit(:state, :city)
    end

    def redis
      @redis ||= Redis.new
    end

    def load_resources
      id = params[:id]||params[:district_audit_id]
      @audit = JSON::parse(redis.get('audit_'+id))
      @results = redis.keys(id+'*').collect{|k| JSON::parse(redis.get(k)) }
    end


end

app/views/district_audits/_total_audit.html.erb
<% percent = (@results.size*100)/@audit["total"] %>

<% if percent < 100 %>
  <div class="progress" style='width: 30%;'>
    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= percent %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= percent %>%;">
      <%= @results.size.to_s + '/' + @audit["total"].to_s %> - <%= percent %>%
    </div>
  </div>
<% else %>
  Total: <%= @audit["total"] %>
<% end %>

app/views/district_audits/index.html.erb
<h1>Mineração de dados</h1>

<%=form_for :audit  do |f| %>
  <%= f.select :state, @states, selected: nil, prompt:"Selecione o Estado" %>
  <%= f.select :city, [], disable:true, prompt:"Selecione a Cidade" %>

  <%= f.submit 'Auditar' %>
<% end %>

<br>
<% @process.each do |p| %>
  <%= link_to district_audit_path(p[:id]) do %>
    <%= p["params"]["state"] %> - <%= p["params"]["city"] %>
  <% end %>
  <br>
<% end %>

app/views/district_audits/show.html.erb
<h3>
<%= @audit["params"]["state"] %> - <%= @audit["params"]["city"] %>
</h3>

<%= render 'total_audit' %>

<br>
<div>
  <% @results.each do |result| %>

    <div class="panel panel-default">
      <div class="panel-heading"><%= result["district"] %></div>
        <div class="list-group">

          <%- result["candidates"].each do |candidate| %>
            <% div_id = Digest::MD5.hexdigest(candidate["candidate_name"]+result["district"]) %>
            <a href="#<%= div_id %>" class="list-group-item" data-toggle="collapse" data-parent="#accordion">
              <span class="badge"><%= candidate["groups"].try(:size).to_i %></span>
              <%= candidate["candidate_name"] %>
            </a>
            <% if candidate["groups"] %>
              <div id="<%= div_id %>" class="panel-collapse collapse">
                <div class="panel-body">
                  <% candidate["groups"].each do |group|%>
                    <%- group.each do |k,v| %>
                      <div class="panel panel-default">
                        <div class="panel-heading">Grupo <%= k %></div>
                        <div class="panel-body">
                          <%= v.collect{|a| "<li>zona: "+a["zone"]+" "+"sessão: "+a["section"]+" "+"Percentual de voto: "+a["calculated"].to_s+'%</li>' }.join("<br>").html_safe %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

    </div>

  <% end %>
</div>

app/views/district_audits/show_in_table.html.erb
<h3>
  <%= @audit["params"]["state"] %> - <%= @audit["params"]["city"] %>
</h3>

<%= render 'total_audit' %>

<table class="table table-bordered" style='width: 40%;'>
  <tr>
    <th>Bairros</th>
    <% @candidates.each do |candidate| %>
      <th><%= candidate["candidate_name"] %></th>
    <% end %>
  </tr>
  <% @results.each do |result| %>
    <tr>
      <td><%= result["district"] %></td>
      <% @candidates.each do |candidate| %>
        <th><%= result["candidates"].select{|c| c["candidate_name"] == candidate["candidate_name"] }[0]["groups"].try(:size).to_i  %></th>
      <% end %>
    </tr>
  <% end %>
</table>