config/routes.rb
ProjetoFinal::Application.routes.draw do
  resources :boletim_urnas
  resources :audits
  resources :district_audits do
    get 'show_in_table' => 'district_audits#show_in_table'
  end
  resources :cities, only: [:index]
  resources :bu, controller: :bulletin_urns_candidates_electoral_sections_political_parties

  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/boletim_urnas_controller.rb
class BoletimUrnasController < ApplicationController
  before_action :set_boletim_urna, only: [:show]

  # GET /boletim_urnas
  # GET /boletim_urnas.json
  def index
    #ids = [25, 26, 34, 73, 94, 98, 128, 147, 173, 210, 268, 364, 374, 377, 380, 397]
    @boletim_urnas = BoletimUrna.summarize_vote_of_candidate_in_the_box#.where(numero_secao: ids)
  end

  # GET /boletim_urnas/1
  # GET /boletim_urnas/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boletim_urna
      @boletim_urna = BoletimUrna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boletim_urna_params
      params[:boletim_urna]
    end
end

app/helpers/boletim_urnas_helper.rb
module BoletimUrnasHelper
end

app/views/boletim_urnas/index.html.erb
<h1>Listing boletim_urnas</h1>

  <% @boletim_urnas.collect(&:numero_de_urna_efetivada).uniq.each do |boletim_urna| %>
  <% urnas = @boletim_urnas.select{|urna| urna.numero_de_urna_efetivada == boletim_urna } %>
    <%= boletim_urna %>
    <%= urnas.last.nome_municipio %>
    Zona: <%= urnas.last.numero_zona %>
    Seção: <%= urnas.last.numero_secao %>
    Quantidade de Comparecimento: <%= urnas.last.quantidade_comparecimento %>
    <%= pie_chart urnas.map{|urna| [urna.nome_do_votavel, urna.quantidade_de_votos] } %>
  <% end %>
<!-- <table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%# @boletim_urnas.each do |boletim_urna| %>
      <tr>
        <td><%#= boletim_urna.numero_de_urna_efetivada %></td>
        <td><%#= boletim_urna.nome_municipio %></td>
        <td><%#= boletim_urna.numero_zona %></td>
        <td><%#= boletim_urna.numero_secao %></td>
        <td><%#= boletim_urna.nome_do_votavel %></td>
        <td><%#= boletim_urna.quantidade_de_votos %></td>
        <!-- <td><%#= link_to 'Show', boletim_urna %></td>
        <td><%#= link_to 'Edit', edit_boletim_urna_path(boletim_urna) %></td>
        <td><%#= link_to 'Destroy', boletim_urna, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Boletim urna', new_boletim_urna_path %>
 -->

app/views/boletim_urnas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_boletim_urna_path(@boletim_urna) %> |
<%= link_to 'Back', boletim_urnas_path %>